#:kivy 2.0.0

ScreenManager:
    Screen:
        ScrollView:
            size_hint: None, None
            size: 500, 1024
            pos_hint: {'center_x': .5, 'center_y': .5}

            GridLayout:
                cols: 2
                padding: 10
                spacing: 10
                height: self.minimum_height
                size_hint: None, None
                do_scroll_x: False
                id: container

<ScrollButton>
    size_hint: None, None
    size: 220, 40